spring:
  config:
    import: optional:application-local.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ongi?serverTimezone=Asia/Seoul
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      format_sql: true
  logging:
    level:
      org.springframework.web: DEBUG

jwt:
  secret: your-secret-key-must-be-very-long-and-secure

coolsms:
  api:
    key: ${SMSKEY}
    secret: ${SMSSECRET}
    number: ${SMSNUMBER}