spring:
  application:
    name: ongi
  config:
    import: optional:application-local.yml
  sql:
    init:
      platform: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      format_sql: true
  logging:
    level:
      org.springframework.web: DEBUG