spring:
  application:
    name: ongi
  config:
    import: optional:application-local.yml
  sql:
    init:
      platform: mysql
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true
  logging:
    level:
      org.springframework.web: DEBUG